### ISSUE TITLE
[v(any 1.21)+loader-0.100.7] Compatibility error with EMI

### ISSUE THREAD

**Issue by MrGII** [TheCSMods/mc-tcdcommons#15]
### What happened?

When opening the inventory in a world that has previous statistics Minecraft crashes, only when EMI and BSS are both enabled (/stats clear @s makes the bug not happen for that session, but that makes BSS useless as the statistics have to be clear every time)

### Steps to reproduce

1. Install EMI and BSS (and its dependecies)
2. Open a world and play it
3. Close the game and reopen it
4. Open the world again
5. Open the inventory
6. Game crashes

### Relevant log output or crash report

```shell
java.lang.IllegalStateException: Item group has no page
    at net.minecraft.class_1761.fabric_getPage(class_1761.java:1096)
    at net.minecraft.class_481.getPage(class_481.java:1214)
    at net.minecraft.class_481.isGroupVisible(class_481.java:1204)
    at net.minecraft.class_481.handler$bmp000$fabric-item-group-api-v1$setSelectedTab(class_481.java:1176)
    at net.minecraft.class_481.method_2466(class_481.java)
    at net.minecraft.class_481.method_25426(class_481.java:439)
    at net.minecraft.class_437.method_25423(class_437.java:309)
    at net.minecraft.class_310.method_1507(class_310.java:1143)
    at net.minecraft.class_490.method_25426(class_490.java:50)
    at net.minecraft.class_437.method_25423(class_437.java:309)
    at net.minecraft.class_310.method_1507(class_310.java:1143)
    at net.minecraft.class_310.method_1508(class_310.java:2068)
    at net.minecraft.class_310.method_1574(class_310.java:1938)
    at net.minecraft.class_310.method_1523(class_310.java:1246)
    at net.minecraft.class_310.method_1514(class_310.java:882)
    at net.minecraft.client.main.Main.main(Main.java:256)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Other installed mods

1. EMI
(others are there but the error was checked without EMI enabled and that showed that's the cause)

### Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by TheCSDev** [comment]
Hello.  
Likely a https://github.com/TheCSMods/mc-better-stats/issues/133 related issue.  
I don't think TCDCommons API on its own would have incompatibility issues. I could be wrong tho, as I didn't check yet.

**Comment by TheCSDev** [comment]
Given this issue is a duplicate, I have decided to close it. Please use the issue I linked to get more info. Hopefully this crash is resolved soon on EMI's end. In the meantime, please keep updating EMI to the latest version in the even they release a patch.
